quarkus.azure-functions.app-name=func-feedback-tech-challenge
quarkus.azure-functions.runtime.java-version=17
quarkus.http.root-path=/api



# ====================================================================
# Configurações do Banco de Dados MySQL (Azure Flexible Server)
# ====================================================================
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}

quarkus.hibernate-orm.database.generation=none

# ====================================================================
# Configurações da Fila (Azure Storage Queue)
# ====================================================================
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.queue-name=${AZURE_STORAGE_QUEUE_NAME}