name: Deploy fn-week-report

on:
  push:
    branches: [ main ]
    paths:
      - 'fn-week-report/**'
      - '.github/workflows/deploy-fn-week-report.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build
        working-directory: fn-week-report
        run: mvn -B -DskipTests -Dquarkus.profile=prod clean package
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: fn-week-report
          package: fn-week-report/target/azure-functions/fn-week-report
          publish-profile: ${{ secrets.PUBLISH_PROFILE_WEEKREPORT }}
