name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fn-feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build
        working-directory: fn-feedback
        run: mvn -B -DskipTests -Dquarkus.profile=prod clean package
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: func-feedback-tech-challenge
          package: fn-feedback/target/azure-functions/func-feedback-tech-challenge
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FEEDBACK }}

  fn-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build
        working-directory: fn-notification
        run: mvn -B -DskipTests -Dquarkus.profile=prod clean package
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: func-notification-tech-challenge
          package: fn-notification/target/azure-functions/func-notification-tech-challenge
          publish-profile: ${{ secrets.PUBLISH_PROFILE_NOTIFICATION }}

  fn-week-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build
        working-directory: fn-week-report
        run: mvn -B -DskipTests -Dquarkus.profile=prod clean package
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: fn-week-report
          package: fn-week-report/target/azure-functions/fn-week-report
          publish-profile: ${{ secrets.PUBLISH_PROFILE_WEEKREPORT }}
